import { router } from 'expo-router';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Screen } from '@/components/Screen';
import { FormField } from '@/components/FormField';
import { GlowButton } from '@/components/GlowButton';
import { useAuthForm } from '@/hooks/useAuthForm';
import { colors, spacing } from '@/theme/tokens';

export function AuthScreen({mode}:{mode:'login'|'signup'}){ const form=useAuthForm(mode); const signup=mode==='signup'; const submit=()=>{if(form.submit()) router.replace('/(tabs)');}; return <Screen scroll><View style={styles.header}><Pressable onPress={()=>router.back()} hitSlop={16}><Ionicons name="arrow-back" color={colors.text} size={24}/></Pressable><Text style={styles.step}>{signup?'JOIN ARAWA':'WELCOME BACK'}</Text></View><View style={styles.copy}><Text style={styles.title}>{signup?'Begin your next chapter.':'Continue creating.'}</Text><Text style={styles.body}>{signup?'A focused space for ideas, people, and possibility.':'Sign in to return to your world.'}</Text></View><View style={styles.form}>{signup&&<FormField label="Name" placeholder="How should we call you?" value={form.name} onChangeText={form.setName} error={form.errors.name} autoComplete="name"/>}<FormField label="Email" placeholder="you@example.com" value={form.email} onChangeText={form.setEmail} error={form.errors.email} keyboardType="email-address" autoCapitalize="none" autoComplete="email"/><FormField label="Password" placeholder="At least 8 characters" value={form.password} onChangeText={form.setPassword} error={form.errors.password} secureTextEntry autoComplete={signup?'new-password':'current-password'}/>{!signup&&<Pressable onPress={()=>Alert.alert('Password reset','Password recovery will be available when authentication is connected.')}><Text style={styles.forgot}>Forgot password?</Text></Pressable>}<GlowButton label={signup?'Create account':'Sign in'} onPress={submit}/><Text style={styles.legal}>{signup?'By continuing, you agree to Arawa’s Terms and Privacy Policy.':'Authentication will connect to the production identity service.'}</Text></View></Screen> }
const styles=StyleSheet.create({header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:spacing.xxl},step:{color:colors.textMuted,fontSize:11,fontWeight:'800',letterSpacing:2},copy:{gap:12,marginBottom:spacing.xl},title:{color:colors.text,fontSize:40,lineHeight:45,fontWeight:'800',letterSpacing:-1.4},body:{color:colors.textMuted,fontSize:17,lineHeight:25},form:{gap:spacing.md},forgot:{color:colors.cyan,textAlign:'right',fontWeight:'700'},legal:{color:colors.textMuted,textAlign:'center',fontSize:12,lineHeight:18,paddingHorizontal:spacing.lg}});

