import { useRef, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { CameraView, useCameraPermissions, type CameraType } from 'expo-camera';
import { Ionicons } from '@expo/vector-icons';
import { Screen } from '@/components/Screen';
import { GlowButton } from '@/components/GlowButton';
import { colors, radii, spacing } from '@/theme/tokens';

export function CameraScreen(){const [permission,requestPermission]=useCameraPermissions(); const [facing,setFacing]=useState<CameraType>('back'); const camera=useRef<CameraView>(null); if(!permission) return <Screen/>; if(!permission.granted) return <Screen style={styles.permission}><View style={styles.permissionIcon}><Ionicons name="camera-outline" size={32} color={colors.cyan}/></View><Text style={styles.permissionTitle}>Camera access</Text><Text style={styles.permissionBody}>Arawa needs permission only when you choose to capture a moment.</Text><GlowButton label="Allow camera" onPress={requestPermission}/></Screen>; const capture=async()=>{const photo=await camera.current?.takePictureAsync({quality:.85});if(photo) Alert.alert('Moment captured','Editing and publishing arrive with the media backend.');}; return <View style={styles.root}><CameraView ref={camera} style={StyleSheet.absoluteFill} facing={facing}/><View style={styles.overlay}><View style={styles.top}><Text style={styles.mode}>MOMENT</Text><Pressable style={styles.round} onPress={()=>setFacing(v=>v==='back'?'front':'back')}><Ionicons name="camera-reverse-outline" size={24} color="#fff"/></Pressable></View><View style={styles.bottom}><Text style={styles.hint}>Tap to capture</Text><Pressable accessibilityLabel="Capture photo" onPress={capture} style={styles.shutterOuter}><View style={styles.shutter}/></Pressable><View style={styles.round}><Ionicons name="images-outline" size={22} color="#fff"/></View></View></View></View>}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:colors.ink},overlay:{flex:1,justifyContent:'space-between',paddingTop:64,paddingBottom:112,paddingHorizontal:spacing.lg,backgroundColor:'rgba(0,0,0,.12)'},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},mode:{color:'#fff',fontWeight:'800',letterSpacing:2},round:{width:46,height:46,borderRadius:23,backgroundColor:'rgba(0,0,0,.38)',alignItems:'center',justifyContent:'center'},bottom:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},hint:{color:'#fff',width:70,fontSize:12},shutterOuter:{width:78,height:78,borderRadius:39,borderWidth:3,borderColor:'#fff',padding:5},shutter:{flex:1,borderRadius:34,backgroundColor:'#fff'},permission:{justifyContent:'center',gap:spacing.md},permissionIcon:{width:64,height:64,borderRadius:radii.md,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},permissionTitle:{color:colors.text,fontSize:30,fontWeight:'800'},permissionBody:{color:colors.textMuted,fontSize:16,lineHeight:24,marginBottom:spacing.md}});

