import { StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Screen } from '@/components/Screen';
import { GlowButton } from '@/components/GlowButton';
import { colors, radii, spacing } from '@/theme/tokens';

export function ProfileScreen(){return <Screen scroll style={styles.screen}><View style={styles.top}><Text style={styles.heading}>Profile</Text><Ionicons name="settings-outline" size={24} color={colors.text}/></View><View style={styles.identity}><View style={styles.avatar}><Ionicons name="person" size={40} color={colors.textMuted}/></View><Text style={styles.name}>Your space</Text><Text style={styles.handle}>Complete your profile when account services connect.</Text></View><View style={styles.stats}><Stat value="—" label="Moments"/><Stat value="—" label="Following"/><Stat value="—" label="Followers"/></View><GlowButton label="Edit profile" variant="secondary"/><View style={styles.section}><Text style={styles.sectionTitle}>Your moments</Text><View style={styles.empty}><Ionicons name="grid-outline" size={28} color={colors.textMuted}/><Text style={styles.emptyTitle}>Ready when you are</Text><Text style={styles.emptyBody}>Captured and published moments will live here.</Text></View></View></Screen>}
function Stat({value,label}:{value:string;label:string}){return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>}
const styles=StyleSheet.create({screen:{paddingBottom:120},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},heading:{color:colors.text,fontSize:28,fontWeight:'800'},identity:{alignItems:'center',marginTop:spacing.xl,gap:8},avatar:{width:94,height:94,borderRadius:47,backgroundColor:colors.surfaceRaised,borderWidth:1,borderColor:colors.line,alignItems:'center',justifyContent:'center'},name:{color:colors.text,fontSize:24,fontWeight:'800',marginTop:8},handle:{color:colors.textMuted,textAlign:'center',maxWidth:300,lineHeight:20},stats:{flexDirection:'row',justifyContent:'space-around',paddingVertical:spacing.lg,marginVertical:spacing.lg,borderTopWidth:1,borderBottomWidth:1,borderColor:colors.line},stat:{alignItems:'center',gap:4},statValue:{color:colors.text,fontSize:20,fontWeight:'800'},statLabel:{color:colors.textMuted,fontSize:12},section:{marginTop:spacing.xl,gap:spacing.md},sectionTitle:{color:colors.text,fontSize:20,fontWeight:'800'},empty:{padding:spacing.xl,alignItems:'center',gap:10,borderRadius:radii.lg,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line},emptyTitle:{color:colors.text,fontSize:17,fontWeight:'700'},emptyBody:{color:colors.textMuted,textAlign:'center'}});

